name: Move Issue to To Do

on:
  issues:
    types: [opened]

jobs:
  move_to_todo:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'To Do' column
        uses: actions/add-to-project@v0.2.1
        with:
          project-url: 'https://github.com/orgs/woorifisa-projects-3rd/projects/6'
          column-name: 'To Do'
          token: ${{ secrets.GITHUB_TOKEN }}
